/**
 * Regenerates src/brands.generated.ts from the provider logos models.dev serves
 * at https://models.dev/logos/<id>.svg — the same registry the catalog and
 * opencode itself are built from.
 *
 * The output is committed, so a build never touches the network. Re-run this
 * after regenerating the catalog:
 *
 *   node scripts/gen-brands.js
 */
const fs = require("fs");
const path = require("path");

const CATALOG = path.join(__dirname, "..", "src", "catalog.ts");
const OUT = path.join(__dirname, "..", "src", "brands.generated.ts");

/** Strips everything the renderer does not need: XML noise, indentation, comments. */
function minify(svg) {
  return svg
    .replace(/<\?xml[^>]*\?>/g, "")
    .replace(/<!--[\s\S]*?-->/g, "")
    .replace(/>\s+</g, "><")
    .replace(/\s{2,}/g, " ")
    .trim();
}

function providerIDs() {
  const src = fs.readFileSync(CATALOG, "utf8");
  const start = src.indexOf("{", src.indexOf("export const CATALOG"));
  const end = src.lastIndexOf("}");
  return Object.keys(JSON.parse(src.slice(start, end + 1))).sort();
}

async function main() {
  const ids = providerIDs();
  const found = {};
  let missing = [];

  for (const id of ids) {
    const res = await fetch(`https://models.dev/logos/${id}.svg`);
    if (!res.ok) {
      missing.push(id);
      continue;
    }
    found[id] = minify(await res.text());
  }

  const body = Object.keys(found)
    .map((id) => `  ${JSON.stringify(id)}: ${JSON.stringify(found[id])},`)
    .join("\n");

  fs.writeFileSync(
    OUT,
    `// Generated by scripts/gen-brands.js from https://models.dev/logos — do not edit.\n` +
      `// ${Object.keys(found).length} of ${ids.length} providers have a logo.\n` +
      `${missing.length ? `// Without one: ${missing.join(", ")}\n` : ""}` +
      `\n/** Provider id -> raw SVG markup, rendered with SvgXml. */\n` +
      `export const GENERATED_BRANDS: Record<string, string> = {\n${body}\n};\n`,
    "utf8",
  );

  console.log(`wrote ${OUT}: ${Object.keys(found).length}/${ids.length} logos`);
  if (missing.length) console.log("without a logo:", missing.join(", "));
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
